/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.awt.Color;
import javax.swing.JOptionPane;
import static sudoku.Sudoku.Asignacion;
import static sudoku.Sudoku.ImprimirMatriz;
import static sudoku.Sudoku.Restantes;

/**
 *
 * @author Rakzodia
 */
public class Inter extends javax.swing.JFrame {

    static void setVisble() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    static void setVisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Inter
     */
    public Inter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
        t00 = new javax.swing.JTextField();
        t01 = new javax.swing.JTextField();
        t02 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t20 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t03 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        t04 = new javax.swing.JTextField();
        t05 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        t15 = new javax.swing.JTextField();
        t23 = new javax.swing.JTextField();
        t24 = new javax.swing.JTextField();
        t25 = new javax.swing.JTextField();
        t21 = new javax.swing.JTextField();
        t22 = new javax.swing.JTextField();
        t18 = new javax.swing.JTextField();
        t26 = new javax.swing.JTextField();
        t27 = new javax.swing.JTextField();
        t28 = new javax.swing.JTextField();
        t06 = new javax.swing.JTextField();
        t16 = new javax.swing.JTextField();
        t07 = new javax.swing.JTextField();
        t08 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        t42 = new javax.swing.JTextField();
        t50 = new javax.swing.JTextField();
        t51 = new javax.swing.JTextField();
        t52 = new javax.swing.JTextField();
        t30 = new javax.swing.JTextField();
        t40 = new javax.swing.JTextField();
        t31 = new javax.swing.JTextField();
        t32 = new javax.swing.JTextField();
        t41 = new javax.swing.JTextField();
        t45 = new javax.swing.JTextField();
        t53 = new javax.swing.JTextField();
        t54 = new javax.swing.JTextField();
        t55 = new javax.swing.JTextField();
        t33 = new javax.swing.JTextField();
        t43 = new javax.swing.JTextField();
        t34 = new javax.swing.JTextField();
        t35 = new javax.swing.JTextField();
        t44 = new javax.swing.JTextField();
        t48 = new javax.swing.JTextField();
        t56 = new javax.swing.JTextField();
        t57 = new javax.swing.JTextField();
        t58 = new javax.swing.JTextField();
        t36 = new javax.swing.JTextField();
        t46 = new javax.swing.JTextField();
        t37 = new javax.swing.JTextField();
        t38 = new javax.swing.JTextField();
        t47 = new javax.swing.JTextField();
        t72 = new javax.swing.JTextField();
        t80 = new javax.swing.JTextField();
        t81 = new javax.swing.JTextField();
        t82 = new javax.swing.JTextField();
        t60 = new javax.swing.JTextField();
        t70 = new javax.swing.JTextField();
        t61 = new javax.swing.JTextField();
        t62 = new javax.swing.JTextField();
        t71 = new javax.swing.JTextField();
        t75 = new javax.swing.JTextField();
        t83 = new javax.swing.JTextField();
        t84 = new javax.swing.JTextField();
        t85 = new javax.swing.JTextField();
        t63 = new javax.swing.JTextField();
        t73 = new javax.swing.JTextField();
        t64 = new javax.swing.JTextField();
        t65 = new javax.swing.JTextField();
        t74 = new javax.swing.JTextField();
        t78 = new javax.swing.JTextField();
        t86 = new javax.swing.JTextField();
        t87 = new javax.swing.JTextField();
        t88 = new javax.swing.JTextField();
        t66 = new javax.swing.JTextField();
        t76 = new javax.swing.JTextField();
        t67 = new javax.swing.JTextField();
        t68 = new javax.swing.JTextField();
        t77 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t00.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        t00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t00ActionPerformed(evt);
            }
        });

        t01.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        t01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t01ActionPerformed(evt);
            }
        });

        t02.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t20.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t12.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t03.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t13.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t04.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t05.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t14.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t15.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t23.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t24.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t25.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        t25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t25ActionPerformed(evt);
            }
        });

        t21.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t22.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t18.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t26.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t27.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t28.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t06.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t16.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t07.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        t07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t07ActionPerformed(evt);
            }
        });

        t08.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        t08.setMaximumSize(new java.awt.Dimension(2, 2));

        t17.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t42.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t50.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t51.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t52.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t30.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t40.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t31.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t32.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t41.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t45.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t53.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t54.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t55.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t33.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t43.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t34.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t35.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t44.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t48.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t56.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        t56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t56ActionPerformed(evt);
            }
        });

        t57.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t58.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        t58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t58ActionPerformed(evt);
            }
        });

        t36.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t46.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t37.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t38.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        t38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t38ActionPerformed(evt);
            }
        });

        t47.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t72.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t80.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t81.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t82.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t60.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t70.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t61.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t62.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t71.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t75.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t83.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t84.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t85.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t63.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t73.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t64.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t65.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t74.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t78.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t86.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t87.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        t87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t87ActionPerformed(evt);
            }
        });

        t88.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t66.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t76.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t67.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t68.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        t77.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        jButton1.setText("Resolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("anterior");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t50, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t30, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t51, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t31, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t52, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t32, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t53, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t33, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t54, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t34, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t55, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t35, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t45, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t56, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t36, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t57, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t37, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t58, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t38, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t20)
                                    .addComponent(t10)
                                    .addComponent(t00, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t01)
                                    .addComponent(t11)
                                    .addComponent(t21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t12)
                                    .addComponent(t02)
                                    .addComponent(t22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t23)
                                    .addComponent(t03)
                                    .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t24)
                                    .addComponent(t04)
                                    .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t25)
                                    .addComponent(t05)
                                    .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t26, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t06, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t27, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t07, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t28, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t08, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t80, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t60, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t70, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t81, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t61, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t71, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t82, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t62, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t72, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t83, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t63, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t73, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t84, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t64, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t74, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t85, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t65, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t75, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t86, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t66, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t76, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t87, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t67, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t77, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t88, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t68, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(t78, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t04)
                            .addComponent(t01)
                            .addComponent(t00)
                            .addComponent(t03)
                            .addComponent(t02)
                            .addComponent(t05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t12)
                            .addComponent(t11)
                            .addComponent(t10)
                            .addComponent(t13)
                            .addComponent(t14)
                            .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t20)
                            .addComponent(t23)
                            .addComponent(t24)
                            .addComponent(t25)
                            .addComponent(t21)
                            .addComponent(t22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t07)
                            .addComponent(t06)
                            .addComponent(t08, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t16)
                            .addComponent(t17)
                            .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t27)
                            .addComponent(t26)
                            .addComponent(t28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t31)
                            .addComponent(t30)
                            .addComponent(t32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t40)
                            .addComponent(t41)
                            .addComponent(t42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t50)
                            .addComponent(t51)
                            .addComponent(t52, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t34)
                            .addComponent(t33)
                            .addComponent(t35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t43)
                            .addComponent(t44)
                            .addComponent(t45, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t54)
                            .addComponent(t53)
                            .addComponent(t55, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t37)
                            .addComponent(t36)
                            .addComponent(t38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t46)
                            .addComponent(t47)
                            .addComponent(t48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t57)
                            .addComponent(t56)
                            .addComponent(t58, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t61)
                            .addComponent(t60)
                            .addComponent(t62, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t70)
                            .addComponent(t71)
                            .addComponent(t72, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t81)
                            .addComponent(t80)
                            .addComponent(t82, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t64)
                            .addComponent(t63)
                            .addComponent(t65, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t73)
                            .addComponent(t74)
                            .addComponent(t75, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t84)
                            .addComponent(t83)
                            .addComponent(t85, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t67)
                            .addComponent(t66)
                            .addComponent(t68, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t76)
                            .addComponent(t77)
                            .addComponent(t78, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t87)
                            .addComponent(t86)
                            .addComponent(t88, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t01ActionPerformed

    private void t00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t00ActionPerformed

    private void t07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t07ActionPerformed

    private void t25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t25ActionPerformed

    private void t38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t38ActionPerformed

    private void t56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t56ActionPerformed

    private void t58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t58ActionPerformed

    private void t87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t87ActionPerformed

    
    void blackt(){
    t00.setForeground(Color.black);
t01.setForeground(Color.black);
t02.setForeground(Color.black);
t03.setForeground(Color.black);
t04.setForeground(Color.black);
t05.setForeground(Color.black);
t06.setForeground(Color.black);
t07.setForeground(Color.black);
t08.setForeground(Color.black);
t10.setForeground(Color.black);
t11.setForeground(Color.black);
t12.setForeground(Color.black);
t13.setForeground(Color.black);
t14.setForeground(Color.black);
t15.setForeground(Color.black);
t16.setForeground(Color.black);
t17.setForeground(Color.black);
t18.setForeground(Color.black);
t20.setForeground(Color.black);
t21.setForeground(Color.black);
t22.setForeground(Color.black);
t23.setForeground(Color.black);
t24.setForeground(Color.black);
t25.setForeground(Color.black);
t26.setForeground(Color.black);
t27.setForeground(Color.black);
t28.setForeground(Color.black);
t30.setForeground(Color.black);
t31.setForeground(Color.black);
t32.setForeground(Color.black);
t33.setForeground(Color.black);
t34.setForeground(Color.black);
t35.setForeground(Color.black);
t36.setForeground(Color.black);
t37.setForeground(Color.black);
t38.setForeground(Color.black);
t40.setForeground(Color.black);
t41.setForeground(Color.black);
t42.setForeground(Color.black);
t43.setForeground(Color.black);
t44.setForeground(Color.black);
t45.setForeground(Color.black);
t46.setForeground(Color.black);
t47.setForeground(Color.black);
t48.setForeground(Color.black);
t50.setForeground(Color.black);
t51.setForeground(Color.black);
t52.setForeground(Color.black);
t53.setForeground(Color.black);
t54.setForeground(Color.black);
t55.setForeground(Color.black);
t56.setForeground(Color.black);
t57.setForeground(Color.black);
t58.setForeground(Color.black);
t60.setForeground(Color.black);
t61.setForeground(Color.black);
t62.setForeground(Color.black);
t63.setForeground(Color.black);
t64.setForeground(Color.black);
t65.setForeground(Color.black);
t66.setForeground(Color.black);
t67.setForeground(Color.black);
t68.setForeground(Color.black);
t70.setForeground(Color.black);
t71.setForeground(Color.black);
t72.setForeground(Color.black);
t73.setForeground(Color.black);
t74.setForeground(Color.black);
t75.setForeground(Color.black);
t76.setForeground(Color.black);
t77.setForeground(Color.black);
t78.setForeground(Color.black);
t80.setForeground(Color.black);
t81.setForeground(Color.black);
t82.setForeground(Color.black);
t83.setForeground(Color.black);
t84.setForeground(Color.black);
t85.setForeground(Color.black);
t86.setForeground(Color.black);
t87.setForeground(Color.black);
t88.setForeground(Color.black);
    }
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        blackt();
        int sudoku[][]=new int[9][9];
        
        if(t00.getText().compareTo("")!=0){
            sudoku[0][0]=Integer.parseInt(t00.getText());
            t00.setForeground(Color.red);
         }
         if(t01.getText().compareTo("")!=0){
           sudoku[0][1]=Integer.parseInt(t01.getText());
           t01.setForeground(Color.red);
        }
        if(t02.getText().compareTo("")!=0){
           sudoku[0][2]=Integer.parseInt(t02.getText());
           t02.setForeground(Color.red);
        }
        if(t03.getText().compareTo("")!=0){
           sudoku[0][3]=Integer.parseInt(t03.getText());
           t03.setForeground(Color.red);
        }
        if(t04.getText().compareTo("")!=0){
           sudoku[0][4]=Integer.parseInt(t04.getText());
           t04.setForeground(Color.red);
        }
        if(t05.getText().compareTo("")!=0){
           sudoku[0][5]=Integer.parseInt(t05.getText());
           t05.setForeground(Color.red);
        }
        if(t06.getText().compareTo("")!=0){
           sudoku[0][6]=Integer.parseInt(t06.getText());
           t06.setForeground(Color.red);
        }
        if(t07.getText().compareTo("")!=0){
           sudoku[0][7]=Integer.parseInt(t07.getText());
           t07.setForeground(Color.red);
        }
        if(t08.getText().compareTo("")!=0){
           sudoku[0][8]=Integer.parseInt(t08.getText());
           t08.setForeground(Color.red);
        }
        if(t10.getText().compareTo("")!=0){
           sudoku[1][0]=Integer.parseInt(t10.getText());
           t10.setForeground(Color.red);
        }
        if(t11.getText().compareTo("")!=0){
           sudoku[1][1]=Integer.parseInt(t11.getText());
           t11.setForeground(Color.red);
        }
        if(t12.getText().compareTo("")!=0){
           sudoku[1][2]=Integer.parseInt(t12.getText());
           t12.setForeground(Color.red);
        }
        if(t13.getText().compareTo("")!=0){
           sudoku[1][3]=Integer.parseInt(t13.getText());
           t13.setForeground(Color.red);
        }
        if(t14.getText().compareTo("")!=0){
           sudoku[1][4]=Integer.parseInt(t14.getText());
           t14.setForeground(Color.red);
        }
        if(t15.getText().compareTo("")!=0){
           sudoku[1][5]=Integer.parseInt(t15.getText());
           t15.setForeground(Color.red);
        }
        if(t16.getText().compareTo("")!=0){
           sudoku[1][6]=Integer.parseInt(t16.getText());
           t16.setForeground(Color.red);
        }
        if(t17.getText().compareTo("")!=0){
           sudoku[1][7]=Integer.parseInt(t17.getText());
           t17.setForeground(Color.red);
        }
        if(t18.getText().compareTo("")!=0){
           sudoku[1][8]=Integer.parseInt(t18.getText());
           t18.setForeground(Color.red);
        }
        if(t20.getText().compareTo("")!=0){
           sudoku[2][0]=Integer.parseInt(t20.getText());
           t20.setForeground(Color.red);
        }
        if(t21.getText().compareTo("")!=0){
           sudoku[2][1]=Integer.parseInt(t21.getText());
           t21.setForeground(Color.red);
        }
        if(t22.getText().compareTo("")!=0){
           sudoku[2][2]=Integer.parseInt(t22.getText());
           t22.setForeground(Color.red);
        }
        if(t23.getText().compareTo("")!=0){
           sudoku[2][3]=Integer.parseInt(t23.getText());
           t23.setForeground(Color.red);
        }
        if(t24.getText().compareTo("")!=0){
           sudoku[2][4]=Integer.parseInt(t24.getText());
           t24.setForeground(Color.red);
        }
        if(t25.getText().compareTo("")!=0){
           sudoku[2][5]=Integer.parseInt(t25.getText());
           t25.setForeground(Color.red);
        }
        if(t26.getText().compareTo("")!=0){
           sudoku[2][6]=Integer.parseInt(t26.getText());
           t26.setForeground(Color.red);
        }
        if(t27.getText().compareTo("")!=0){
           sudoku[2][7]=Integer.parseInt(t27.getText());
           t27.setForeground(Color.red);
        }
        if(t28.getText().compareTo("")!=0){
           sudoku[2][8]=Integer.parseInt(t28.getText());
           t28.setForeground(Color.red);
        }
        if(t30.getText().compareTo("")!=0){
           sudoku[3][0]=Integer.parseInt(t30.getText());
           t30.setForeground(Color.red);
        }
        if(t31.getText().compareTo("")!=0){
           sudoku[3][1]=Integer.parseInt(t31.getText());
           t31.setForeground(Color.red);
        }
        if(t32.getText().compareTo("")!=0){
           sudoku[3][2]=Integer.parseInt(t32.getText());
           t32.setForeground(Color.red);
        }
        if(t33.getText().compareTo("")!=0){
           sudoku[3][3]=Integer.parseInt(t33.getText());
           t33.setForeground(Color.red);
        }
        if(t34.getText().compareTo("")!=0){
           sudoku[3][4]=Integer.parseInt(t34.getText());
           t34.setForeground(Color.red);
        }
        if(t35.getText().compareTo("")!=0){
           sudoku[3][5]=Integer.parseInt(t35.getText());
           t35.setForeground(Color.red);
        }
        if(t36.getText().compareTo("")!=0){
           sudoku[3][6]=Integer.parseInt(t36.getText());
           t36.setForeground(Color.red);
        }
        if(t37.getText().compareTo("")!=0){
           sudoku[3][7]=Integer.parseInt(t37.getText());
           t37.setForeground(Color.red);
        }
        if(t38.getText().compareTo("")!=0){
           sudoku[3][8]=Integer.parseInt(t38.getText());
           t38.setForeground(Color.red);
        }
        if(t40.getText().compareTo("")!=0){
           sudoku[4][0]=Integer.parseInt(t40.getText());
           t40.setForeground(Color.red);
        }
        if(t41.getText().compareTo("")!=0){
           sudoku[4][1]=Integer.parseInt(t41.getText());
           t41.setForeground(Color.red);
        }
        if(t42.getText().compareTo("")!=0){
           sudoku[4][2]=Integer.parseInt(t42.getText());
           t42.setForeground(Color.red);
        }
        if(t43.getText().compareTo("")!=0){
           sudoku[4][3]=Integer.parseInt(t43.getText());
           t43.setForeground(Color.red);
        }
        if(t44.getText().compareTo("")!=0){
           sudoku[4][4]=Integer.parseInt(t44.getText());
           t44.setForeground(Color.red);
        }
        if(t45.getText().compareTo("")!=0){
           sudoku[4][5]=Integer.parseInt(t45.getText());
           t45.setForeground(Color.red);
        }
        if(t46.getText().compareTo("")!=0){
           sudoku[4][6]=Integer.parseInt(t46.getText());
           t46.setForeground(Color.red);
        }
        if(t47.getText().compareTo("")!=0){
           sudoku[4][7]=Integer.parseInt(t47.getText());
           t47.setForeground(Color.red);
        }
        if(t48.getText().compareTo("")!=0){
           sudoku[4][8]=Integer.parseInt(t48.getText());
           t48.setForeground(Color.red);
        }
        if(t50.getText().compareTo("")!=0){
           sudoku[5][0]=Integer.parseInt(t50.getText());
           t50.setForeground(Color.red);
        }
        if(t51.getText().compareTo("")!=0){
           sudoku[5][1]=Integer.parseInt(t51.getText());
           t51.setForeground(Color.red);
        }
        if(t52.getText().compareTo("")!=0){
           sudoku[5][2]=Integer.parseInt(t52.getText());
           t52.setForeground(Color.red);
        }
        if(t53.getText().compareTo("")!=0){
           sudoku[5][3]=Integer.parseInt(t53.getText());
           t53.setForeground(Color.red);
        }
        if(t54.getText().compareTo("")!=0){
           sudoku[5][4]=Integer.parseInt(t54.getText());
           t54.setForeground(Color.red);
        }
        if(t55.getText().compareTo("")!=0){
           sudoku[5][5]=Integer.parseInt(t55.getText());
           t55.setForeground(Color.red);
        }
        if(t56.getText().compareTo("")!=0){
           sudoku[5][6]=Integer.parseInt(t56.getText());
           t56.setForeground(Color.red);
        }
        if(t57.getText().compareTo("")!=0){
           sudoku[5][7]=Integer.parseInt(t57.getText());
           t57.setForeground(Color.red);
        }
        if(t58.getText().compareTo("")!=0){
           sudoku[5][8]=Integer.parseInt(t58.getText());
           t58.setForeground(Color.red);
        }
        if(t60.getText().compareTo("")!=0){
           sudoku[6][0]=Integer.parseInt(t60.getText());
           t60.setForeground(Color.red);
        }
        if(t61.getText().compareTo("")!=0){
           sudoku[6][1]=Integer.parseInt(t61.getText());
           t61.setForeground(Color.red);
        }
        if(t62.getText().compareTo("")!=0){
           sudoku[6][2]=Integer.parseInt(t62.getText());
           t62.setForeground(Color.red);
        }
        if(t63.getText().compareTo("")!=0){
           sudoku[6][3]=Integer.parseInt(t63.getText());
           t63.setForeground(Color.red);
        }
        if(t64.getText().compareTo("")!=0){
           sudoku[6][4]=Integer.parseInt(t64.getText());
           t64.setForeground(Color.red);
        }
        if(t65.getText().compareTo("")!=0){
           sudoku[6][5]=Integer.parseInt(t65.getText());
           t65.setForeground(Color.red);
        }
        if(t66.getText().compareTo("")!=0){
           sudoku[6][6]=Integer.parseInt(t66.getText());
           t66.setForeground(Color.red);
        }
        if(t67.getText().compareTo("")!=0){
           sudoku[6][7]=Integer.parseInt(t67.getText());
           t67.setForeground(Color.red);
        }
        if(t68.getText().compareTo("")!=0){
           sudoku[6][8]=Integer.parseInt(t68.getText());
           t68.setForeground(Color.red);
        }
        if(t70.getText().compareTo("")!=0){
           sudoku[7][0]=Integer.parseInt(t70.getText());
           t70.setForeground(Color.red);
        }
        if(t71.getText().compareTo("")!=0){
           sudoku[7][1]=Integer.parseInt(t71.getText());
           t71.setForeground(Color.red);
        }
        if(t72.getText().compareTo("")!=0){
           sudoku[7][2]=Integer.parseInt(t72.getText());
           t72.setForeground(Color.red);
        }
        if(t73.getText().compareTo("")!=0){
           sudoku[7][3]=Integer.parseInt(t73.getText());
           t73.setForeground(Color.red);
        }
        if(t74.getText().compareTo("")!=0){
           sudoku[7][4]=Integer.parseInt(t74.getText());
           t74.setForeground(Color.red);
        }
        if(t75.getText().compareTo("")!=0){
           sudoku[7][5]=Integer.parseInt(t75.getText());
           t75.setForeground(Color.red);
        }
        if(t76.getText().compareTo("")!=0){
           sudoku[7][6]=Integer.parseInt(t76.getText());
           t76.setForeground(Color.red);
        }
        if(t77.getText().compareTo("")!=0){
           sudoku[7][7]=Integer.parseInt(t77.getText());
           t77.setForeground(Color.red);
        }
        if(t78.getText().compareTo("")!=0){
           sudoku[7][8]=Integer.parseInt(t78.getText());
           t78.setForeground(Color.red);
        }
        if(t80.getText().compareTo("")!=0){
           sudoku[8][0]=Integer.parseInt(t80.getText());
           t80.setForeground(Color.red);
        }
        if(t81.getText().compareTo("")!=0){
           sudoku[8][1]=Integer.parseInt(t81.getText());
           t81.setForeground(Color.red);
        }
        if(t82.getText().compareTo("")!=0){
           sudoku[8][2]=Integer.parseInt(t82.getText());
           t82.setForeground(Color.red);
        }
        if(t83.getText().compareTo("")!=0){
           sudoku[8][3]=Integer.parseInt(t83.getText());
           t83.setForeground(Color.red);
        }
        if(t84.getText().compareTo("")!=0){
           sudoku[8][4]=Integer.parseInt(t84.getText());
           t84.setForeground(Color.red);
        }
        if(t85.getText().compareTo("")!=0){
           sudoku[8][5]=Integer.parseInt(t85.getText());
           t85.setForeground(Color.red);
        }
        if(t86.getText().compareTo("")!=0){
           sudoku[8][6]=Integer.parseInt(t86.getText());
           t86.setForeground(Color.red);
        }
        if(t87.getText().compareTo("")!=0){
           sudoku[8][7]=Integer.parseInt(t87.getText());
           t87.setForeground(Color.red);
        }
        if(t88.getText().compareTo("")!=0){
           sudoku[8][8]=Integer.parseInt(t88.getText());
           t88.setForeground(Color.red);
        }
        
        int band=Restantes(sudoku);
        while(true)
        {
        
        for(int i=0;i<9;i++)
            for(int j=0;j<9;j++)
		if(sudoku[i][j]==0)
                    Asignacion(sudoku,i,j);
        
        
        if(Restantes(sudoku)==band)
            break;
        band=Restantes(sudoku);
        
        }
        
        if(Restantes(sudoku)==0)
        {
            System.out.println("Sodoku Resuelto");
            //imprimir
            imp(sudoku);
        }
        else
        {
            JOptionPane.showMessageDialog(null,  "Este sudoku no se puede Resolver","Irresoluble", JOptionPane.ERROR_MESSAGE);
            System.out.println("Sodoku Hasta donde se pudo");
            ImprimirMatriz(sudoku);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        limpiar();
        blackt();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    void limpiar(){
    t00.setText("");
t01.setText("");
t02.setText("");
t03.setText("");
t04.setText("");
t05.setText("");
t06.setText("");
t07.setText("");
t08.setText("");
t10.setText("");
t11.setText("");
t12.setText("");
t13.setText("");
t14.setText("");
t15.setText("");
t16.setText("");
t17.setText("");
t18.setText("");
t20.setText("");
t21.setText("");
t22.setText("");
t23.setText("");
t24.setText("");
t25.setText("");
t26.setText("");
t27.setText("");
t28.setText("");
t30.setText("");
t31.setText("");
t32.setText("");
t33.setText("");
t34.setText("");
t35.setText("");
t36.setText("");
t37.setText("");
t38.setText("");
t40.setText("");
t41.setText("");
t42.setText("");
t43.setText("");
t44.setText("");
t45.setText("");
t46.setText("");
t47.setText("");
t48.setText("");
t50.setText("");
t51.setText("");
t52.setText("");
t53.setText("");
t54.setText("");
t55.setText("");
t56.setText("");
t57.setText("");
t58.setText("");
t60.setText("");
t61.setText("");
t62.setText("");
t63.setText("");
t64.setText("");
t65.setText("");
t66.setText("");
t67.setText("");
t68.setText("");
t70.setText("");
t71.setText("");
t72.setText("");
t73.setText("");
t74.setText("");
t75.setText("");
t76.setText("");
t77.setText("");
t78.setText("");
t80.setText("");
t81.setText("");
t82.setText("");
t83.setText("");
t84.setText("");
t85.setText("");
t86.setText("");
t87.setText("");
t88.setText("");
    }
    
    
    
    
    void imp(int sudoku[][]){
    t00.setText(String.valueOf(sudoku[0][0]));
t01.setText(String.valueOf(sudoku[0][1]));
t02.setText(String.valueOf(sudoku[0][2]));
t03.setText(String.valueOf(sudoku[0][3]));
t04.setText(String.valueOf(sudoku[0][4]));
t05.setText(String.valueOf(sudoku[0][5]));
t06.setText(String.valueOf(sudoku[0][6]));
t07.setText(String.valueOf(sudoku[0][7]));
t08.setText(String.valueOf(sudoku[0][8]));
t10.setText(String.valueOf(sudoku[1][0]));
t11.setText(String.valueOf(sudoku[1][1]));
t12.setText(String.valueOf(sudoku[1][2]));
t13.setText(String.valueOf(sudoku[1][3]));
t14.setText(String.valueOf(sudoku[1][4]));
t15.setText(String.valueOf(sudoku[1][5]));
t16.setText(String.valueOf(sudoku[1][6]));
t17.setText(String.valueOf(sudoku[1][7]));
t18.setText(String.valueOf(sudoku[1][8]));
t20.setText(String.valueOf(sudoku[2][0]));
t21.setText(String.valueOf(sudoku[2][1]));
t22.setText(String.valueOf(sudoku[2][2]));
t23.setText(String.valueOf(sudoku[2][3]));
t24.setText(String.valueOf(sudoku[2][4]));
t25.setText(String.valueOf(sudoku[2][5]));
t26.setText(String.valueOf(sudoku[2][6]));
t27.setText(String.valueOf(sudoku[2][7]));
t28.setText(String.valueOf(sudoku[2][8]));
t30.setText(String.valueOf(sudoku[3][0]));
t31.setText(String.valueOf(sudoku[3][1]));
t32.setText(String.valueOf(sudoku[3][2]));
t33.setText(String.valueOf(sudoku[3][3]));
t34.setText(String.valueOf(sudoku[3][4]));
t35.setText(String.valueOf(sudoku[3][5]));
t36.setText(String.valueOf(sudoku[3][6]));
t37.setText(String.valueOf(sudoku[3][7]));
t38.setText(String.valueOf(sudoku[3][8]));
t40.setText(String.valueOf(sudoku[4][0]));
t41.setText(String.valueOf(sudoku[4][1]));
t42.setText(String.valueOf(sudoku[4][2]));
t43.setText(String.valueOf(sudoku[4][3]));
t44.setText(String.valueOf(sudoku[4][4]));
t45.setText(String.valueOf(sudoku[4][5]));
t46.setText(String.valueOf(sudoku[4][6]));
t47.setText(String.valueOf(sudoku[4][7]));
t48.setText(String.valueOf(sudoku[4][8]));
t50.setText(String.valueOf(sudoku[5][0]));
t51.setText(String.valueOf(sudoku[5][1]));
t52.setText(String.valueOf(sudoku[5][2]));
t53.setText(String.valueOf(sudoku[5][3]));
t54.setText(String.valueOf(sudoku[5][4]));
t55.setText(String.valueOf(sudoku[5][5]));
t56.setText(String.valueOf(sudoku[5][6]));
t57.setText(String.valueOf(sudoku[5][7]));
t58.setText(String.valueOf(sudoku[5][8]));
t60.setText(String.valueOf(sudoku[6][0]));
t61.setText(String.valueOf(sudoku[6][1]));
t62.setText(String.valueOf(sudoku[6][2]));
t63.setText(String.valueOf(sudoku[6][3]));
t64.setText(String.valueOf(sudoku[6][4]));
t65.setText(String.valueOf(sudoku[6][5]));
t66.setText(String.valueOf(sudoku[6][6]));
t67.setText(String.valueOf(sudoku[6][7]));
t68.setText(String.valueOf(sudoku[6][8]));
t70.setText(String.valueOf(sudoku[7][0]));
t71.setText(String.valueOf(sudoku[7][1]));
t72.setText(String.valueOf(sudoku[7][2]));
t73.setText(String.valueOf(sudoku[7][3]));
t74.setText(String.valueOf(sudoku[7][4]));
t75.setText(String.valueOf(sudoku[7][5]));
t76.setText(String.valueOf(sudoku[7][6]));
t77.setText(String.valueOf(sudoku[7][7]));
t78.setText(String.valueOf(sudoku[7][8]));
t80.setText(String.valueOf(sudoku[8][0]));
t81.setText(String.valueOf(sudoku[8][1]));
t82.setText(String.valueOf(sudoku[8][2]));
t83.setText(String.valueOf(sudoku[8][3]));
t84.setText(String.valueOf(sudoku[8][4]));
t85.setText(String.valueOf(sudoku[8][5]));
t86.setText(String.valueOf(sudoku[8][6]));
t87.setText(String.valueOf(sudoku[8][7]));
t88.setText(String.valueOf(sudoku[8][8]));
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField t00;
    private javax.swing.JTextField t01;
    private javax.swing.JTextField t02;
    private javax.swing.JTextField t03;
    private javax.swing.JTextField t04;
    private javax.swing.JTextField t05;
    private javax.swing.JTextField t06;
    private javax.swing.JTextField t07;
    private javax.swing.JTextField t08;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t21;
    private javax.swing.JTextField t22;
    private javax.swing.JTextField t23;
    private javax.swing.JTextField t24;
    private javax.swing.JTextField t25;
    private javax.swing.JTextField t26;
    private javax.swing.JTextField t27;
    private javax.swing.JTextField t28;
    private javax.swing.JTextField t30;
    private javax.swing.JTextField t31;
    private javax.swing.JTextField t32;
    private javax.swing.JTextField t33;
    private javax.swing.JTextField t34;
    private javax.swing.JTextField t35;
    private javax.swing.JTextField t36;
    private javax.swing.JTextField t37;
    private javax.swing.JTextField t38;
    private javax.swing.JTextField t40;
    private javax.swing.JTextField t41;
    private javax.swing.JTextField t42;
    private javax.swing.JTextField t43;
    private javax.swing.JTextField t44;
    private javax.swing.JTextField t45;
    private javax.swing.JTextField t46;
    private javax.swing.JTextField t47;
    private javax.swing.JTextField t48;
    private javax.swing.JTextField t50;
    private javax.swing.JTextField t51;
    private javax.swing.JTextField t52;
    private javax.swing.JTextField t53;
    private javax.swing.JTextField t54;
    private javax.swing.JTextField t55;
    private javax.swing.JTextField t56;
    private javax.swing.JTextField t57;
    private javax.swing.JTextField t58;
    private javax.swing.JTextField t60;
    private javax.swing.JTextField t61;
    private javax.swing.JTextField t62;
    private javax.swing.JTextField t63;
    private javax.swing.JTextField t64;
    private javax.swing.JTextField t65;
    private javax.swing.JTextField t66;
    private javax.swing.JTextField t67;
    private javax.swing.JTextField t68;
    private javax.swing.JTextField t70;
    private javax.swing.JTextField t71;
    private javax.swing.JTextField t72;
    private javax.swing.JTextField t73;
    private javax.swing.JTextField t74;
    private javax.swing.JTextField t75;
    private javax.swing.JTextField t76;
    private javax.swing.JTextField t77;
    private javax.swing.JTextField t78;
    private javax.swing.JTextField t80;
    private javax.swing.JTextField t81;
    private javax.swing.JTextField t82;
    private javax.swing.JTextField t83;
    private javax.swing.JTextField t84;
    private javax.swing.JTextField t85;
    private javax.swing.JTextField t86;
    private javax.swing.JTextField t87;
    private javax.swing.JTextField t88;
    // End of variables declaration//GEN-END:variables
}
